//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.03 at 11:50:50 PM EET 
//

package ua.ronaldo173.mypackage;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="diagonal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="brightness" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="resolution">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="1920x1080"/>
 *               &lt;enumeration value="2560x1080"/>
 *               &lt;enumeration value="1600x1900"/>
 *               &lt;enumeration value="1366x768"/>
 *               &lt;enumeration value="1280x1024"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "model", "diagonal", "brightness", "resolution", "price" })
@XmlRootElement(name = "monitor")
public class Monitor {

	@XmlElement(required = true)
	protected String model;
	@XmlElement(required = true)
	protected BigDecimal diagonal;
	@XmlElement(required = true)
	protected BigDecimal brightness;
	@XmlElement(required = true)
	protected String resolution;
	@XmlElement(required = true)
	protected BigDecimal price;

	/**
	 * Gets the value of the model property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getModel() {
		return model;
	}

	/**
	 * Sets the value of the model property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setModel(String value) {
		this.model = value;
	}

	/**
	 * Gets the value of the diagonal property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getDiagonal() {
		return diagonal;
	}

	/**
	 * Sets the value of the diagonal property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setDiagonal(BigDecimal value) {
		this.diagonal = value;
	}

	/**
	 * Gets the value of the brightness property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getBrightness() {
		return brightness;
	}

	/**
	 * Sets the value of the brightness property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setBrightness(BigDecimal value) {
		this.brightness = value;
	}

	/**
	 * Gets the value of the resolution property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getResolution() {
		return resolution;
	}

	/**
	 * Sets the value of the resolution property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setResolution(String value) {
		this.resolution = value;
	}

	/**
	 * Gets the value of the price property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * Sets the value of the price property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setPrice(BigDecimal value) {
		this.price = value;
	}

}
